blogapp/articles/urls.py
from django.urls import path

from articles.views import AddArticleView, EditArticleView,\
    ArticleApprovalView, ArticleStatusView, EditedArticlesView

urlpatterns = [
    path('article/add/', AddArticleView.as_view(), name='add'),
    path('article/<pk>/', EditArticleView.as_view(), name='edit'),
    path('article-approval/', ArticleApprovalView.as_view(), name='approval'),
    path('articles-edited/',
         EditedArticlesView.as_view(), name='articles-edited'),
    path('article/<pk>/approve/', ArticleStatusView.as_view(), name='approve'),
    path('article/<pk>/reject/', ArticleStatusView.as_view(), name='reject')
]

blogapp/blogapp/urls.py
from django.contrib import admin
from django.urls import path, include

from blogapp.views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', DashboardView.as_view(), name='dashboard'),
    path('', include('users.urls'),),
    path('', include(('articles.urls', "articles"), namespace="articles"))
]

blogapp/users/urls.py
from django.urls import path, include

from users.views import RegisterView

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", RegisterView.as_view(), name="register")
]

blogapp/templates/base.html
{% load static %}
<html>
    <head>
        <title>{% block title %} {% endblock %}</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!--Bootstrap CSS-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        {% block style %} {% endblock %}
    </head>
    <body>
        {% if messages %}
            {% for message in messages %}
                <div class="container-fluid p-0">
                    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                        <button type="button" class="close"  data-bs-dismiss="alert" aria-label="Close">
                            <span aria-hidden="True">&times;</span>
                        </button>
                        {{ message }}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}

        <!-- Optional Javascript -->
        {% block scripts %} {% endblock %}
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

blogapp/templates/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block title %}Dashboard{% endblock %}
{% block style %}
    <link rel="stylesheet" type='text/css' href="{% static 'basic.css' %}">
{% endblock %}

{% block content %}
    <div class="container py-5">
        <h1>Writters</h1>
        <table>
            <tr>
                <th class="left-align-col">Writer</th>
                <th>Total Articles Written</th>
                <th>Total Articles Written Last 30</th>
            </tr>
            {% for writer in object_list %}
                <tr>
                    <td class="left-align-col">{{ writer.name }}</td>
                    <td>{{ writer.articles_total }}</td>
                    <td>{{ writer.articles_last_30_days }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td>No articles yet.</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="container py-3">
        {% if user.is_authenticated %}
            <p>Hi {{ user.name }}!<p></p>
            <p><a href="{% url 'articles:add' %}">Add Article</a></p>
            {% if user.is_editor %}
                <p><a href="{% url 'articles:approval' %}">Approval Page</a></p>
                <p><a href="{% url 'articles:articles-edited' %}">Edited Articles</a></p>
            {% endif %}
            <p><a href="{% url 'logout' %}">Log Out</a></p>
        {% else %}
            <p>You are not logged in</p>
            <p><a href="{% url 'login' %}">Log In</a> or <a href="{% url 'register' %}">Register</a></p>
        {% endif %}
    </div>
{% endblock %}