blogapp/articles/urls.py
from django.urls import path

from articles.views import AddArticleView, EditArticleView,\
    ArticleApprovalView, ArticleStatusView, EditedArticlesView

urlpatterns = [
    path('article/add/', AddArticleView.as_view(), name='add'),
    path('article/<pk>/', EditArticleView.as_view(), name='edit'),
    path('article-approval/', ArticleApprovalView.as_view(), name='approval'),
    path('articles-edited/',
         EditedArticlesView.as_view(), name='articles-edited'),
    path('article/<pk>/approve/', ArticleStatusView.as_view(), name='approve'),
    path('article/<pk>/reject/', ArticleStatusView.as_view(), name='reject')
]

blogapp/blogapp/urls.py
from django.contrib import admin
from django.urls import path, include

from blogapp.views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', DashboardView.as_view(), name='dashboard'),
    path('', include('users.urls'),),
    path('', include(('articles.urls', "articles"), namespace="articles"))
]

blogapp/users/urls.py
from django.urls import path, include

from users.views import RegisterView

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", RegisterView.as_view(), name="register")
]

blogapp/articles/models.py
from django.db import models

IN_PROGRESS = 0
APPROVED = 1
REJECTED = 2
STATUS_CHOICES = (
    (IN_PROGRESS, "In progress"),
    (APPROVED, "Approved"),
    (REJECTED, "Rejected")
)


class Article(models.Model):
    """Model containing data of blog posts"""
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100, blank=False, null=False)
    content = models.TextField(blank=False, null=False)
    status = models.IntegerField(
        choices=STATUS_CHOICES, default=IN_PROGRESS, blank=False)
    written_by = models.ForeignKey(
        "users.Writer", on_delete=models.CASCADE,
        related_name="articles_written")
    edited_by = models.ForeignKey(
        "users.Writer", on_delete=models.CASCADE,
        related_name="articles_edited", blank=True, null=True)

    class Meta:
        permissions = [
            ("create", "Can create a new article"),
            ("edit", "Can edit an article"),
            ("approve/reject", "Can approve or reject an article")
        ]

blogapp/articles/forms.py
from django import forms
from articles.models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        self.fields['status'].disabled = True
        self.fields['written_by'].disabled = True
        self.fields['edited_by'].disabled = True
        if not (instance and instance.pk):
            self.fields['status'].widget = forms.HiddenInput()
            self.fields['written_by'].widget = forms.HiddenInput()
            self.fields['edited_by'].widget = forms.HiddenInput()
            self.fields['written_by'].required = False

blogapp/articles/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse, resolve
from django.utils import timezone
from django.views import View
from django.views.generic import FormView, UpdateView, ListView

from articles.forms import ArticleForm
from articles.models import Article, APPROVED, REJECTED, IN_PROGRESS


class AjaxView(View):
    """Required the request to be ajax"""

    def dispatch(self, request, *args, **kwargs):
        if not request.is_ajax:
            messages.error(request, "Not a ajax request")
            return HttpResponseRedirect(reverse('dashboard'))
        return super().dispatch(request, *args, **kwargs)


class EditorRequiredView(LoginRequiredMixin, View):

    def dispatch(self, request, *args, **kwargs):
        if not getattr(request.user, "is_editor", False):
            messages.error(request, "You are not an editor")
            return HttpResponseRedirect(reverse('dashboard'))
        return super().dispatch(request, *args, **kwargs)

    def handle_no_permission(self):
        messages.error(self.request, self.permission_denied_message)
        return HttpResponseRedirect(reverse('dashboard'))


class ApprovalMixin(EditorRequiredView, PermissionRequiredMixin):
    """Requires that the user is authenticated, has the 'approve/reject'
        permission and is an editor"""
    permission_required = 'articles.approve/reject'
    permission_denied_message = \
        "You do not have the permission to approve/reject articles"

    def handle_no_permission(self):
        messages.error(self.request, self.permission_denied_message)
        return HttpResponseRedirect(reverse('dashboard'))


class AddArticleView(PermissionRequiredMixin, LoginRequiredMixin, FormView):
    """Article creation FormView"""
    permission_required = 'articles.create'
    permission_denied_message = \
        "You do not have the permission to add articles"
    template_name = 'articles/add.html'
    form_class = ArticleForm
    success_url = '/'

    def form_valid(self, form):
        request = self.request
        article = form.save(commit=False)
        article.written_by = request.user
        article.save()
        messages.success(request, "Article added.")
        return super().form_valid(form)

    def handle_no_permission(self):
        messages.error(self.request, self.permission_denied_message)
        return HttpResponseRedirect(reverse('dashboard'))


class EditArticleView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    """Article UpdateView"""
    permission_required = 'articles.edit'
    permission_denied_message = \
        "You do not have the permission to edit articles"
    template_name = 'articles/edit.html'
    model = Article
    form_class = ArticleForm
    success_url = '/'

    def form_valid(self, form):
        request = self.request
        article = form.save(commit=False)
        article.edited_by = request.user
        article.save()
        messages.success(request, "Article edited.")
        return super().form_valid(form)

    def handle_no_permission(self):
        messages.error(self.request, self.permission_denied_message)
        return HttpResponseRedirect(reverse('dashboard'))


class ArticleApprovalView(ApprovalMixin, ListView):
    """Returns list of all 'IN_PROGRESS'
        (neither approved or rejected) articles."""
    template_name = 'articles/approval.html'
    model = Article

    def get_queryset(self):
        return Article.objects.filter(status=IN_PROGRESS).order_by('pk')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class EditedArticlesView(EditorRequiredView, ListView):
    """Returns list of all edited articles."""
    template_name = 'articles/edited.html'
    model = Article

    def get_queryset(self):
        return Article.objects.filter(
            edited_by=self.request.user).order_by('pk')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class ArticleStatusView(ApprovalMixin, AjaxView):
    """Approve or reject article. AJAX required"""

    def post(self, request, *args, **kwargs):
        current_url = resolve(request.path_info).view_name
        article = get_object_or_404(Article, pk=self.kwargs['pk'])
        # Not the best solution. But it works for now
        if current_url == "articles:approve":
            article.status = APPROVED
            messages.success(request, "Article approved.")
        else:
            article.status = REJECTED
            messages.warning(request, "Article rejected.")
        article.save()

        return JsonResponse({})

blogapp/templates/articles/add.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Add Article{% endblock %}
{% block style %}

{% endblock %}

{% block content %}
    <div class="container py-5">
        <h1>Add Article</h1>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Add</button>
            <button id="goBack" type="button" class="btn btn-info float-right" onclick="history.back()">Back</button>
        </form>
    <div>
{% endblock %}

blogapp/templates/articles/approval.html
{% extends "base.html" %}
{% load static %}

{% block title %}Approval Page{% endblock %}
{% block style %}
    <link rel="stylesheet" type='text/css' href="{% static 'basic.css' %}">
{% endblock %}

{% block content %}
    <div class="container py-5">
        <h1>Articles</h1>
        <table>
            <tr>
                <th class="writer-col">ID</th>
                <th class="writer-col">Title</th>
                <th>Status</th>
                <th>Written By</th>
                <th>Edited By</th>
                <th>Edit</th>
                <th>Approve</th>
                <th>Reject</th>
            </tr>
            {% for article in object_list %}
                <tr>
                    <td class="writer-col">{{ article.pk }}</td>
                    <td class="writer-col">{{ article.title }}</td>
                    <td>{{ article.get_status_display }}</td>
                    <td>{{ article.written_by|default_if_none:"--" }}</td>
                    <td>{{ article.edited_by|default_if_none:"--" }}</td>
                    <td>
                        <button type="button" class="btn btn-info" onclick=edit({{ article.pk }})>
                            <i class="fa fa-pencil" aria-hidden="true"></i>
                        </button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-success" onclick=approve({{ article.pk }})>
                            <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                        </button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-danger" onclick=reject({{ article.pk }})>
                            <i class="fa fa-thumbs-down" aria-hidden="true"></i>
                        </button>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td>No articles yet.</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="container py-3">
        <button id="goBack" type="button" class="btn btn-info float-right" onclick="history.back()">Back</button>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        function reload() {
            location.reload();
            return false;
        }

        function ajax_request(url) {
            $.ajax({
                type: 'POST',
                url: url,
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
            })
            reload();
        }

        function edit(pk) {
            location.href = "{% url 'articles:edit' 0 %}".replace("0", pk);
        }

        function approve(pk) {
            ajax_request("{% url 'articles:approve' 0 %}".replace("0", pk));
        }

        function reject(pk) {
            ajax_request("{% url 'articles:reject' 0 %}".replace("0", pk));
        }
    </script>
{% endblock %}

blogapp/templates/articles/edit.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Edit Article{% endblock %}
{% block style %}

{% endblock %}

{% block content %}
    <div class="container py-5">
        <h1>Add Article</h1>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Save</button>
            <button id="goBack" type="button" class="btn btn-info float-right" onclick="history.back()">Back</button>
        </form>
    <div>
{% endblock %}

blogapp/templates/articles/edited.html
{% extends "base.html" %}
{% load static %}

{% block title %}Edited articles{% endblock %}
{% block style %}
    <link rel="stylesheet" type='text/css' href="{% static 'basic.css' %}">
{% endblock %}

{% block content %}
    <div class="container py-5">
        <h1>Edited articles</h1>
        <table>
            <tr>
                <th class="writer-col">ID</th>
                <th class="writer-col">Title</th>
                <th>Status</th>
                <th>Written By</th>
                <th>Edited By</th>
                <th>Edit</th>
            </tr>
            {% for article in object_list %}
                <tr>
                    <td class="writer-col">{{ article.pk }}</td>
                    <td class="writer-col">{{ article.title }}</td>
                    <td>{{ article.get_status_display }}</td>
                    <td>{{ article.written_by|default_if_none:"--" }}</td>
                    <td>{{ article.edited_by|default_if_none:"--" }}</td>
                    <td>
                        <button type="button" class="btn btn-info" onclick=edit({{ article.pk }})>
                            <i class="fa fa-pencil" aria-hidden="true"></i>
                        </button>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td>No articles yet.</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="container py-3">
        <button id="goBack" type="button" class="btn btn-info float-right" onclick="history.back()">Back</button>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        function reload() {
            location.reload();
            return false;
        }

        function ajax_request(url) {
            $.ajax({
                type: 'POST',
                url: url,
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
            })
            reload();
        }

        function edit(pk) {
            location.href = "{% url 'articles:edit' 0 %}".replace("0", pk);
        }
    </script>
{% endblock %}